datapoint/datapoint.go
event/event.go
event/event_test.go

and a few spelling mistakes in comments

Add events

---

event/event.go
event/event_test.go

as jenny said it predates dimensions and why create another place to clean up

remove source

---

.travis.yml
boltcycle/boltcycle.go
boltcycle/boltcycle_test.go
disco/thrift.go
disco/thrift_test.go
goverify.json

Updated travis should make test failures more consistent.  Boltcycle
allows us to do a read optimized LRU

Add boltcycle library and update travis

---

gobuild.toml
sfxclient/gobuild.toml
web/bucketreqcounter.go
web/bucketreqcounter_test.go

Add request counter that uses a p90 bucket

---

circle.sh
gobuild.toml
sfxclient/datapointcreation.go
sfxclient/httpsink.go
sfxclient/httpsink_test.go
sfxclient/sfxclient.go
sfxclient/sfxclient_test.go

Default dims and zero times weren't being handled correctly

sfxclient fixes

---

disco/disco.go
disco/disco_test.go

Allows me to run local disco code with debug flags that go explicitly to specific hosts.

Add service instance overrides

---

gobuild.toml
log/filter.go
log/filter_test.go
log/filterexample_test.go
log/json.go

A log that passes through only if filters match, and a HTTP handler for changing filters

Initially working filters

---

.gitignore
sfxclient/integration_test.go
sfxclient/sfxclient.go

Add integration test that allows testing datapoint sending directly.

Add integration test

---

datapoint/dpsink/logfilter.go
datapoint/dptest/generator.go
event/event.go

an oversight when extending collectd notification…s to events

Meta -> Properties

---

README.md

Add link to SDK in top-level readme

Link to SDK from top-level readme

---

disco/disco.go
disco/disco_test.go
disco/thrift.go

*disco.Service.ServiceInstances() now returns a predictable order on elements
Add ability to delete an advertised service and to do so on close.
Add ability to try to find a next connection at a specific offset.

Some disco/thrift enhancements

---

datapoint/datapoint.go
datapoint/datapoint_test.go
datapoint/dpsink/logfilter.go
datapoint/dpsink/logfilter_test.go
sfxclient/httpsink.go
sfxclient/httpsink_test.go

summary: 'Property' attribute in Datapoint was experimental and never
supported. The commit will remove support for the same.
test: ran all unit test cases & removed any test case which was handling
property

Do not extract properties from datapoints 'Meta' attribute

---

env/env.go
env/env_test.go

Add utility functions for reading environment variables

env: Add env package with env var utility functions

---

trace/translator/batcher.go
trace/translator/batcher_test.go
trace/translator/sfx.go
trace/translator/sfx_test.go

* export various utility functions from trace translator
* export the SpanBatcher's bucket map

export utility functions from trace translator

---

go-metrics/exporter.go
go-metrics/exporter_test.go

Ability to extract dimensions in go-metrics exporter
- can pass in custom parsers to accomplish this job

Extract dimensions in go-metrics exporter

---

trace/translator/sfx.go
trace/translator/sfx_test.go

There are only 3 possible tags in processTags and N+4 in total. Allocate an N+4 slice and fill spanTags initially then processTags.
```
benchmark                           old ns/op     new ns/op     delta
BenchmarkSFXTagsToJaegerTags-16     1178          753           -36.08%
benchmark                           old allocs     new allocs     delta
BenchmarkSFXTagsToJaegerTags-16     2              1              -50.00%
benchmark                           old bytes     new bytes     delta
BenchmarkSFXTagsToJaegerTags-16     3840          2304          -40.00%
```

Fix length of allocated slices in SFXTagsToJaegerTags

---

sfxclient/rollbucket.go

I've literally never used these ever, not once. You can turn them on by
setting obj.IncludeSum = true if you want them but off by default

Make sfxclient.RollingBucket not defaultly send in Sum and SumOfSquares

---

sfxclient/spanfilter/spanfilter.go

This is intended to be used for RUM initially.

Add span filter error for missing required tags

---

go.mod
go.sum
metadata/hostmetadata/host.go
metadata/hostmetadata/host_test.go

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

Upgrade to use gopsutil/v3

---

disco/disco.go
disco/disco_test.go

This will help with logging in apps that use this module.

disco: Add Name method to Service object

---

go.mod
go.sum

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

Bump github.com/signalfx/com_signalfx_metrics_protobuf to latest

---

disco/disco_test.go
errors/compatibility_test.go
go.mod
go.sum
sfxclient/multitokensink_test.go

This dependency is most used as test and has an incompatible license.

Remove juju/errors dependency
