distconf/distconf.go
distconf/distconf_test.go

The old code used to continue looking for valid config values
in lower backing stores when an update at a higher level
contained an invalid value. This could cause a simple typo to
revert a distconf variable to another state, which could
be bad(tm). Now on an invalid value the current value of the
config is kept.
Also refactored distconf unit test so that adding a new type
will be easier to test.

distconf - Fallback to last known good value when invalid config

---

schedexec/schedexec.go
schedexec/schedexec_test.go

schedexec is a library for running code on a schedule.
Both fixed and variable rate schedules are supported

Add schedexec

---

.travis.yml
circle.sh
disco/disco_test.go
log/hierarchy.go
log/hierarchy_test.go

While on, it is messing up go-junit-report's ability to create junit XML
reports from stdout/stderr.

Allow disabling default logger

---

sfxclient/httpsink.go

This morning we started receiving a lot of `invalid status code: 400` errors, and it was difficult to debug. This PR adds the response body to the `error` returned when the API returns a non-200 status code.

add response body on HTTP errors

---

.travis.yml
README.md
circle.sh
clientcfg/client.go
clientcfg/client_test.go
gobuild.toml
logkey/keys.go
reportSHA/reportsha.go
reportSHA/reportsha_test.go
sfxclient/multitokensink.go
sfxclient/multitokensink_test.go

* Add reportSHA and clientcfg pkgs
* Add additional log keys
* Drop compatibility for golang v 1.4 (for dependency go-kit)
* Add additional go versions to travis and cirlceci
* Extend test timeout to 30 sec
* Fix CI scripts to use Thrift v0.9.3
* Ignore go vet error "unrecognized verb 'n'" found in sprintf statement
* Upgrade gobuild to v1.7
* Replace aligncheck gobuild config with maligned

add asynchronous multitoken sink for emitting with different tokens

---

sfxclient/multitokensink.go
sfxclient/multitokensink_test.go

Long Explanation:
The design of the multitoken sink is now a sink that has X number of input channels.  The token sent in with a datapoint is hashed to a channel, and then there are Y number of datapoint / event worker threads that drain the channel.

specify # of workers draining each input channel of the multitoken sink

---

sfxclient/httpsink.go

According to [the documentation](https://developers.signalfx.com/v2/reference#section-criteria-for-metric-and-dimension-names-and-values) hyphens are allowed in dimension keys, but the protobof encoding for HTTPClient disallows them. This modifies the allowed characters to include `-`.
cc @mdubbyap

Add hyphen to allowed characters for dimension keys

---

datapoint/dpsink/logfilter.go
expvar2/handler.go
sfxclient/README.md
sfxclient/httpsink.go
sfxclient/httpsink_test.go
sfxclient/multitokensink.go

The current code pulls out the `ctx.Done` function to handle request timeouts, but doesn't attach the context to the request itself. This gets in the way of things like net/http/httptrace. Instead, we should be using `WithContext`, which handles timeouts, and also exposes the context to other stuff. [This](https://github.com/stripe/veneur/commit/71e9438a7e5b015a2feb5f6f67168712ec7cd948) is a concrete example of why the context needs to be attached to the request.
The `*http.Client` change is mostly for hygiene (clients should usually be shared), but I can remove that commit if maintainers prefer.

Use WithContext instead of Cancel for http requests

---

pdbcycle/pdbcycle.go

summary: when we read locations during Read() call, we had two loops.
One was incrementing stats information and other was updating return
value. Both the iterations was on same data slice. If we look at system
as a whole there are multiple go-routines calling this Read api for
multiple datum's. Having one iteration should speed some cpu time by a
small factor.
test: ran all unit test cases

pdbcycle: removed extra iteration of read locations

---

Gopkg.lock
Gopkg.toml
clientcfg/client.go
sfxclient/sfxclient.go
sfxclient/sfxclient_test.go
vendor/github.com/opentracing/opentracing-go/LICENSE
vendor/github.com/opentracing/opentracing-go/globaltracer.go
vendor/github.com/opentracing/opentracing-go/gocontext.go
vendor/github.com/opentracing/opentracing-go/log/field.go
vendor/github.com/opentracing/opentracing-go/log/util.go
vendor/github.com/opentracing/opentracing-go/noop.go
vendor/github.com/opentracing/opentracing-go/propagation.go
vendor/github.com/opentracing/opentracing-go/span.go
vendor/github.com/opentracing/opentracing-go/tracer.go

summary: opentracing support is added to debug "sf.metrics""
datapoints collections. To enable/disable debugging call Debug(). Also added is
"ReportingTimeoutInterval", which will log error messages if the
datapoint collection is not completed within configured duration. To update
duration call ReportingTimeout()
vendor: added opentracing-go v1.1.0 dependency via dep
test: added new unit test cases to test debug mode & reporting interval
timeout error message

sfxclient debugging support

---

env/env.go
env/env_test.go

I think there is benefit to keeping the default argument as a pointer.  Specifically in the gateway, where we are passing in a pointer to a loaded config value which may or may not be nil.
I do think that these functions shouldn't blindly return the default argument as is.  Instead they should return a pointer to a copy of the default argument's value.  Hopefully this will help reduce confusion since the functions are returning pointers to values, instead of setting the value at a specified pointer.

make env package functions return copies of their pointed default values

---

logkey/keys.go

when a service is using disco package it passes DiscoService name which
ended up overwriting context service value to DiscoService.

logkey: changing DiscoService value to "disco_service"

---

datapoint/dpsink/counter.go
datapoint/dpsink/counter_test.go

When a spanfilter is returned we were still counting the full # of spans in the payload, not just the invalid number that was returned in the spanfilter.

Fix downstream counter count

---

sfxclient/sfxclient.go
sfxclient/sfxclient_test.go

We're using this CollectDatapoints() function in the gateway's internal metrics listener.  I just ran some tests with the go race detector and it detected a data race around our use of scheduler.CollectDatapoints().  This pr addresses that.

make scheduler.CollectDatapoints() lock the callback mutex

---

sfxclient/sfxclient.go

scheduler.ReportOnce prefixes datapoints with a configured prefix.  This pr makes scheduler.CollectDatapoints() also prefix datapoints for consistent behavior.

prefix datapoints in scheduler.CollectDatapoints

---

metadata/hostmetadata/host.go
metadata/hostmetadata/host_test.go

WMI is sometimes slow on Windows and a box was observed taking 4 seconds to
return instead of the library default of 3.
As a first pass I've just made it a default timeout of 10 for everything for
CPU metadata. I could limit this to just apply to Windows or I could add a new
API that takes context in and punt the decision to the caller (in this case
it will be the sfx agent). Anybody have an opinion?

Increase CPU metadata query to 10 seconds from default of 3

---

.travis.yml
datapoint/datapoint.go
datapoint/datapoint_test.go

Those changes allow to unmarshal MetricType from text and to print its value using human friendly text. 
When it comes to JSON encoding there is no change in current behaviour: MetricType is encoded as number.

Add stringer and unmarshallers for MetricType type

---

log/log.go

Currently, we have a dynamic log key called Caller.  The default value (DefaultCaller) has a preconfigured number of stack frames to skip in order to print the calling function.  
All of the log.IfErr...() functions were adding another frame that DefaultCaller did not take into account.  
We can't increase the number of frames to skip in DefaultCaller because clients use logger.Log() directly where the number of frames to skip is correct.
The only solution is to make the IfErr..s convert the incoming logger to *Context and create the log statement directly instead of invoking Log() as a middle person().

make log.IfErr (and friends) fetch the dynamic keys so log.Caller is correct

---

go.sum
sfxclient/httpsink.go

Updated span validator function to accept empty body in response so it
can export spans in zipkin format to any valid zipkin destination in
addition to the SignalFx backend.
Alternatively, we can make the spans validator pluggable in HTTP Sink so
a separate "zipkinClient` can reuse most of it.

Update spans validator to accept empty body as a valid response

---

.travis.yml
go.mod
go.sum
sfxclient/README.md
translator/batcher.go
translator/batcher_test.go
translator/constants.go
translator/grpc_http_mapper.go
translator/grpc_http_mapper_test.go
translator/sfx.go
translator/sfx_test.go

dependency
temporarily excluding translator from 100% coverage.

moving translator from signalfx/sapm-proto to golib to avoid circular

---

trace/translator/sfx.go
trace/translator/sfx_test.go

Span kind strings may be lowercase, which wouldn't match any of the
switch case statements. This change ensures we ToUpper the kind string
beforehand.

correctly translate span kinds regardless of string case

---

sfxclient/httpsink.go
sfxclient/multitokensink.go

Some information from SignalFx could be used to help the client to decide what to do on failure:
- 429 is only returned by the ingestion data points when a limit has been reached of metrics or event rates. 
- There is a Throttle-Type header returned with the 429 which indicates what the reason was for the 429 to be returned.
- There is a Retry-After header returned with the 429 which indicates the backoff time which should be used.

add TooManyRequestError to sfxclient

---

sfxclient/httpsink.go

This change extends the existing SFXAPIError struct by adding two extra
fields 'token' and 'endpoint'. This allows for custom error
handlers that can behave differently depending on the token or endpoint
associated with the error. In the AsyncMultiTokenSink case, this error
handler is only called when the underlying client can't successfully
call the ingestion endpoint after the configured number of retries.
An example of where this could be useful:
The token for SignalFx ingestion is being throttled, so report the
error directly to cloudwatch so we can alert on it, with the token
and endpoint affected as dimensions for more targeted alerting.

Extend SFXAPIError to include endpoint

---

sfxclient/wrapper.go
sfxclient/wrapper_test.go

When you init a slice with a certain length and then use append,
it doesn't overwrite the initial entries created, it just adds more
entries after them.

Fix slice init bug causing initial nil entries

---

sfxclient/httpsink.go
sfxclient/httpsink_test.go
sfxclient/spanfilter/spanfilter.go
trace/translator/sfx.go
trace/translator/sfx_test.go

- because the jaeger format can't express bad ids (except 0s) this is the best way to ship this information back
- also annotate with a few other errors

Now populate a context with a spanfilter when turning zipkin into sapm

---

trace/translator/sfx.go
trace/translator/sfx_test.go

Apply same logic as in the ingest-protocols repository in the "v2AnnotationsToJaegerLogs" function. That needs now to be updated and not check for error.
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

Fix conversion bug for annotations to sapm logs, when not JSON

---

go.mod
go.sum

Bring this fix in https://github.com/signalfx/com_signalfx_metrics_protobuf/commit/5ce916896c1a14ed97d0a59411ff87212d34ef08
Signed-off-by: Dani Louca <dlouca@splunk.com>

update com_signalfx_metrics_protobuf to 0.0.2 to prevent a conflict with Jaeger protobuf name

---

web/closeheader.go
web/servicestate.go
web/servicestate_test.go

currently web handler was only setting connection close if the service was
in graceful shutdown. If not then it was assuming the service to be healthy and
sending in http request downstream. This can potentially lead to leaking of incoming http
requests to the backed end service.
Migrating CloseHeader to ServiceState which will add Connection Header if the service
is in graceful shutdown regardless of the request being GET or POST. Additional
support includes setting the state as 503 when called. This allows the service to
reject any incoming http request when ALB still thinks the service is healthy due
to the fact that refresh is not yet kicked in.
Test: Added test cases to handle the different GET & POST scenarios for all 3 states of
the service

web: adding service state support

---

disco/disco_test.go
zkplus/zkplus.go
zkplus/zkplus_test.go

This will avoid more issues when dealing wiht read-only root nodes

zkplus: Always check for existence even if creates allowed

---

sfxclient/httpsink.go
sfxclient/httpsink_test.go

It would be helpful to be able to get the underlying errors on failed submissions to improve retry behavior in the smart agent.

httpsink: wrap network errors

---

go.mod
go.sum
web/reqcounter.go
web/reqcounter_test.go

This makes those metrics reusable between HTTP and gRPC servers

Add gRPC interceptor to request tracker

---

sfxclient/httpsink.go
sfxclient/httpsink_test.go

some headers in the request can potentially contain secure credentials.
Added api loggableHeaders() which will extract out such headers that
should not be logged.

sfxclient: http sink upon error should not log all request headers

---

.github/workflows/golangci-lint.yml
.golangci.yml
distconf/mem.go
explorable/explorable.go
log/ratelimit.go
sfxclient/httpsink.go
sfxclient/httpsink_test.go
trace/translator/sfx_test.go

Apparently the version we were on had a bug with the typecheck linter.

Fix golangci-lint issues by upgrading + fixing new stuff
